import type { Metadata } from "next";

import "./globals.css";

import React from "react";

// Metadata for the app
export const metadata: Metadata = {
  title: "Sreyas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
